export const mockPlayers = [
    {
    "player_id": 8444894,
    "first_name": "Greg",
    "last_name": "Adams",
    "nationality": "CAN",
    "birth_city": "Nelson",
    "primary_position": "LW",
    "birth_date": "1963-08-15T01:00:00.000Z",
    "birth_state_province": "BC",
    "height": "6' 4",
    "height_cm": "193.04",
    "weight": "196",
    "shoots_catches": "L"
    },
    {
    "player_id": 8444919,
    "first_name": "Tommy",
    "last_name": "Albelin",
    "nationality": "SWE",
    "birth_city": "Stockholm",
    "primary_position": "D",
    "birth_date": "1964-05-21T01:00:00.000Z",
    "birth_state_province": null,
    "height": "6' 2",
    "height_cm": "187.96",
    "weight": "195",
    "shoots_catches": "L"
    },
    {
    "player_id": 8445000,
    "first_name": "Dave",
    "last_name": "Andreychuk",
    "nationality": "CAN",
    "birth_city": "Hamilton",
    "primary_position": "LW",
    "birth_date": "1963-09-29T01:00:00.000Z",
    "birth_state_province": "ON",
    "height": "6' 4",
    "height_cm": "193.04",
    "weight": "225",
    "shoots_catches": "R"
    },
    {
    "player_id": 8445176,
    "first_name": "Donald",
    "last_name": "Audette",
    "nationality": "CAN",
    "birth_city": "Laval",
    "primary_position": "RW",
    "birth_date": "1969-09-23T01:00:00.000Z",
    "birth_state_province": "QC",
    "height": "5' 8",
    "height_cm": "172.72",
    "weight": "191",
    "shoots_catches": "R"
    },
    {
    "player_id": 8445266,
    "first_name": "Murray",
    "last_name": "Baron",
    "nationality": "CAN",
    "birth_city": "Prince George",
    "primary_position": "D",
    "birth_date": "1967-06-01T01:00:00.000Z",
    "birth_state_province": "BC",
    "height": "6' 3",
    "height_cm": "190.5",
    "weight": "236",
    "shoots_catches": "L"
    },
    {
    "player_id": 8445275,
    "first_name": "Tom",
    "last_name": "Barrasso",
    "nationality": "USA",
    "birth_city": "Boston",
    "primary_position": "G",
    "birth_date": "1965-03-31T01:00:00.000Z",
    "birth_state_province": "MA",
    "height": "6' 3",
    "height_cm": "190.5",
    "weight": "210",
    "shoots_catches": "R"
    },
    {
    "player_id": 8445283,
    "first_name": "Len",
    "last_name": "Barrie",
    "nationality": "CAN",
    "birth_city": "Kimberley",
    "primary_position": "C",
    "birth_date": "1969-06-04T01:00:00.000Z",
    "birth_state_province": "BC",
    "height": "6' 0",
    "height_cm": "182.88",
    "weight": "200",
    "shoots_catches": "L"
    },
    {
    "player_id": 8445386,
    "first_name": "Ed",
    "last_name": "Belfour",
    "nationality": "CAN",
    "birth_city": "Carman",
    "primary_position": "G",
    "birth_date": "1965-04-21T01:00:00.000Z",
    "birth_state_province": "MB",
    "height": "6' 0",
    "height_cm": "182.88",
    "weight": "214",
    "shoots_catches": "L"
    },
    {
    "player_id": 8445413,
    "first_name": "Drake",
    "last_name": "Berehowsky",
    "nationality": "CAN",
    "birth_city": "Toronto",
    "primary_position": "D",
    "birth_date": "1972-01-03T00:00:00.000Z",
    "birth_state_province": "ON",
    "height": "6' 2",
    "height_cm": "187.96",
    "weight": "217",
    "shoots_catches": "R"
    },
    {
    "player_id": 8445423,
    "first_name": "Benoit",
    "last_name": "Hogue",
    "nationality": "CAN",
    "birth_city": "Repentigny",
    "primary_position": "LW",
    "birth_date": "1966-10-28T00:00:00.000Z",
    "birth_state_province": "QC",
    "height": "5' 10",
    "height_cm": "177.8",
    "weight": "194",
    "shoots_catches": "L"
    }
]